# Generated by Django 2.0.2 on 2018-05-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glaciers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massif_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='glacier',
            name='massif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='glaciers.Massif'),
        ),
    ]
