# Generated by Django 2.0.2 on 2018-05-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glaciers', '0002_auto_20180515_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='glacier',
            name='glacier_area',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='glacier',
            name='glacier_length',
            field=models.FloatField(default=0),
        ),
    ]
