# Generated by Django 2.0.2 on 2018-05-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=200)),
                ('visit_title', models.CharField(max_length=200)),
                ('visit_year', models.IntegerField()),
            ],
        ),
    ]
