# Generated by Django 2.0.2 on 2018-05-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visitor_name',
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor_first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor_last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
